config/routes.rb
Rails.application.routes.draw do
resources :favorites, only: [:create, :destroy]
resources :sessions, only: [:new, :create, :destroy]
resources :users, only: [:new, :create, :show]
resources :posts do
  collection do
    post :confirm
    patch :confirm
  end
    member do
      patch :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :content, presence: true, length: { in: 1..140 }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :favorites, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper
    before_action :login_required

    private

    def login_required
      redirect_to new_session_path unless current_user
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if params[:back]
      render :new
    else
      if @post.save
      redirect_to posts_path, notice: "つぶやきました！"
      else
      render :new
      end
    end
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice:"削除しました！"
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, notice: "編集しました！"
    else
      render :edit
    end
  end

  def confirm
    @post = current_user.posts.build(post_params)
    render :new if @post.invalid?
  end

    private

  def post_params
  params.require(:post).permit(:content)
  end

  def set_post
  @post = Post.find(params[:id])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      confirm_post_path
    end
  end

  def confirm_new_or_edit
    unless @post.id?
      posts_path
    else
      post_path
    end
  end

  def confirm_form_method
    @post.id ? 'patch' : 'post'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kei</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <header>
    <p>ゆんたく</p>
  </header>

  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>

      <%= yield %>
  </div>

  <footer>
	<p>2022 DIC.WEF_2205</p>
  </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit  "つぶやく" %>
<% end %>

<%= link_to "一覧画面にもどる", posts_path %>

app/views/posts/confirm.html.erb
<h3>以下の内容で、つぶやく</h3>

<%= form_with(model: @post,　url:posts_path, local: true) do |form| %>
  <%= form.hidden_field :content %>

  <p>本文:<%= @post.content %></p>
  <%= form.submit  "つぶやく" %>
  <%= form.submit "戻る", name: 'back' %>

  <%= link_to '一覧画面に戻る', posts_path %>

<% end %>

app/views/posts/edit.html.erb
<%= form_with(model: @post, local: true,url:confirm_posts_path) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= @post.errors.count %>件のエラーがあります。</h2>
      <h2>編集する</h2>

      <%= render 'form' %>
      <ul>

      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      <h2>編集する</h2>

      <%= render 'form' %>
      </ul>
    </div>
  <% end %>

  <div class="post_content">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit  "つぶやく" %>
<% end %>
<%= link_to '一覧画面に戻る', posts_path %>

app/views/posts/index.html.erb
<h1>ゆんたく一覧</h1>

<p><%= notice %></p>

<table>
  <tr>
    <th>ゆんたく内容</th>
    <th>名前</th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.content %></td>
    <td><%= post.user.name %></td>

    <td><%= link_to '詳細', post_path(post.id) %></td>
    <td><%= link_to "編集", edit_post_path(post.id) %></td>
    <td><%= link_to '削除', post_path(post.id), method: :delete,data: { confirm: '本当に削除していいですか？' } %></td>

  </tr>
<% end %>
</table>
<%= link_to 'ツイートする', new_post_path %>

app/views/posts/new.html.erb
  <h2>つぶやく</h2>

  <%= render 'form' %>

app/views/posts/show.html.erb
<h1>詳細画面</h1>
<p>名前:<%= @post.user.name %></p>
<p>内容: <%= @post.content %></p>

<% unless @post.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入り', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to '一覧画面に戻る', posts_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス: <%= @user.email %></p>
<%= link_to "Top", posts_path%>